Import Libraries — Code cell

In [3]:
import pandas as pd
import numpy as np

Upload the CSV File — Code cell

In [23]:
# Load CSV file
df = pd.read_csv("Day7_Student_Dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

Load the Dataset — Code cell

Display the Dataset — Code cell
## 1. First Few Rows

The `head()` function displays the first few rows of the dataset.
By default, it displays the first 5 rows

In [5]:
df.head()
#You can also display a specific number of rows:
df.head(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

Last Few Rows — Markdown cell
## 2. Last Few Rows

The `tail()` function displays the last few rows of the dataset.

In [6]:
df.tail()
#For the last 10 rows:
df.tail(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

Random Samples — Markdown cell
## 3. Random Samples

The `sample()` function is useful for viewing randomly selected records from the dataset.

In [7]:
df.sample(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad

Dataset Shape — Markdown cell
## 4. Dataset Shape

The `shape` attribute returns the number of rows and columns in the dataset.

Format:

(rows, columns)

In [8]:
rows, columns = df.shape

print("Number of rows:", rows)
print("Number of columns:", columns)
print("Dataset shape:", df.shape)

Number of rows: 25
Number of columns: 7
Dataset shape: (25, 7)

Column Names — Markdown cell
## 5. Dataset Columns

The `columns` attribute displays the names of all features/columns in the dataset.

In [9]:
print("Column names:")
print(df.columns)

#For a cleaner list:

for column in df.columns:
    print(column)

Column names:
Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='str')
Student_ID
Name
Age
Course
Marks
Attendance_Percentage
City

Dataset Index — Markdown cell
## 6. Dataset Index

The `index` attribute provides information about the DataFrame index.

In [10]:
print("Dataset Index:")
print(df.index)

Dataset Index:
RangeIndex(start=0, stop=25, step=1)

Data Types — Markdown cell
## 7. Data Types

The `dtypes` attribute shows the data type of each column.

In [11]:
print("Data Types:")
print(df.dtypes)

Data Types:
Student_ID                 int64
Name                         str
Age                        int64
Course                       str
Marks                    float64
Attendance_Percentage    float64
City                         str
dtype: object

Dataset Information — Markdown cell
## 8. Dataset Information

The `info()` function provides important information about the DataFrame, including:

- Number of entries
- Column names
- Non-null values
- Data types
- Memory usage

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     str
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     str
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     str
dtypes: float64(2), int64(2), str(3)
memory usage: 1.5 KB

Descriptive Statistics — Markdown cell
## 9. Descriptive Statistics

The `describe()` function generates statistical information for numerical columns.

It includes:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median (50%)
- 75th percentile
- Maximum

In [13]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

Statistics for All Columns — Code cell

In [14]:
df.describe(include="all")

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
count,25.000000,25,25.000000,25,24.000000,24.000000,24
unique,NaN,25,NaN,3,NaN,NaN,13
top,NaN,Aarav Sharma,NaN,Data Science,NaN,NaN,Srinagar
freq,NaN,1,NaN,9,NaN,NaN,6
mean,1013.000000,NaN,20.000000,NaN,82.250000,87.083333,NaN
std,7.359801,NaN,1.414214,NaN,8.689074,7.252686,NaN
min,1001.000000,NaN,18.000000,NaN,68.000000,72.000000,NaN
25%,1007.000000,NaN,19.000000,NaN,75.500000,82.750000,NaN
50%,1013.000000,NaN,20.000000,NaN,82.500000,88.000000,NaN
75%,1019.000000,NaN,21.000000,NaN,89.250000,92.250000,NaN
max,1025.000000,NaN,23.000000,NaN,96.000000,98.000000,NaN

Check Missing Values — Markdown cell
## 10. Missing Value Analysis

Missing values can affect data analysis and machine learning.

The `isnull().sum()` function calculates the number of missing values in each column.

In [15]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

Missing Value Percentage — Code cell

In [16]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing value percentage:")
print(missing_percentage)

Missing value percentage:
Student_ID               0.0
Name                     0.0
Age                      0.0
Course                   0.0
Marks                    4.0
Attendance_Percentage    4.0
City                     4.0
dtype: float64

Display Only Columns with Missing Values — Code cell

In [17]:
missing = df.isnull().sum()

missing = missing[missing > 0]

if len(missing) == 0:
    print("No missing values found in the dataset.")
else:
    print("Columns containing missing values:")
    print(missing)

Columns containing missing values:
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

Check Duplicate Rows — Markdown cell
## 11. Duplicate Row Analysis

The `duplicated()` function can be used to identify duplicate records.

In [18]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

Number of Unique Values — Markdown cell
## 12. Unique Values

The `nunique()` function shows the number of unique values in each column.

In [19]:
print("Number of unique values in each column:")
print(df.nunique())

Number of unique values in each column:
Student_ID               25
Name                     25
Age                       6
Course                    3
Marks                    24
Attendance_Percentage    22
City                     13
dtype: int64

Numerical Columns — Code cell

In [20]:
numerical_columns = df.select_dtypes(include=np.number).columns

print("Numerical columns:")
print(list(numerical_columns))

Numerical columns:
['Student_ID', 'Age', 'Marks', 'Attendance_Percentage']

Categorical/Text Columns — Code cell

In [21]:
categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns

print("Categorical/Text columns:")
print(list(categorical_columns))

Categorical/Text columns:
['Name', 'Course', 'City']

C:\Users\jeswi\AppData\Local\Temp\ipykernel_21004\3747364486.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

Summary Table — Code cell

In [22]:
summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Non-Null Count": df.notnull().sum().values,
    "Missing Count": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

summary

,Column,Data Type,Non-Null Count,Missing Count,Unique Values
0,Student_ID,int64,25,0,25
1,Name,str,25,0,25
2,Age,int64,25,0,6
3,Course,str,25,0,3
4,Marks,float64,24,1,24
5,Attendance_Percentage,float64,24,1,22
6,City,str,24,1,13

Automatic Dataset Observations
## 13. Basic Observations

The following section summarizes the main characteristics of the dataset.

In [24]:
print("DATASET SUMMARY")

print(f"Number of rows    : {df.shape[0]}")
print(f"Number of columns : {df.shape[1]}")

print("\nFeatures:")
for column in df.columns:
    print("-", column)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
missing = df.isnull().sum()

for column, count in missing.items():
    if count > 0:
        print(f"- {column}: {count} missing value(s)")

if missing.sum() == 0:
    print("No missing values found.")

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nNumerical Columns:")
print(list(df.select_dtypes(include=np.number).columns))

print("\nCategorical Columns:")
print(list(df.select_dtypes(include=["object", "category"]).columns))

DATASET SUMMARY
Number of rows    : 25
Number of columns : 7

Features:
- Student_ID
- Name
- Age
- Course
- Marks
- Attendance_Percentage
- City

Data Types:
Student_ID                 int64
Name                         str
Age                        int64
Course                       str
Marks                    float64
Attendance_Percentage    float64
City                         str
dtype: object

Missing Values:
- Marks: 1 missing value(s)
- Attendance_Percentage: 1 missing value(s)
- City: 1 missing value(s)

Duplicate Rows:
0

Numerical Columns:
['Student_ID', 'Age', 'Marks', 'Attendance_Percentage']

Categorical Columns:
['Name', 'Course', 'City']

C:\Users\jeswi\AppData\Local\Temp\ipykernel_21004\567498494.py:30: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(list(df.select_dtypes(include=["object", "category"]).columns))